### ISSUE TITLE
implicit declaration error

### ISSUE THREAD

**Issue by nobu-g** [ku-nlp/knp#3]
Mac でコンパイル時に次のような implicit declaration error が複数出力される
```
case_analysis.c:1078:5: error: implicit declaration of function 'bnst_to_tag_tree' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    bnst_to_tag_tree(sp);
```

macOS Bug Sur (11.0.1)
```
$ clang -v
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by nobu-g** [comment]
clang のエラー検出の default 設定が厳しくなっているよう
WORKAROUND: `./configure CFLAGS=-w`

**Comment by eiennohito** [comment]
おそらく、それよりは `--std=c89` でコンパイルしたほうがいいです。

**Comment by nobu-g** [comment]
`./configure CFLAGS=--std=c89` としてコンパイルしてみましたが、implicit declaration error が出ます。

**Comment by h-keisuke** [comment]
`CFLAGS=-w` もしくは `CFLAGS=-Wno-implicit-function-declaration` でコンパイルエラーは回避できるのを確認しました。

```bash
% clang -v
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

しかし、実行時エラーになってしまいました。別問題かもしれませんが。

```bash
% echo "下鴨神社の参道は暗かった。" | jumanpp | knp -tab
zsh: done                echo "下鴨神社の参道は暗かった。" | jumanpp |
zsh: segmentation fault  knp -tab
```

**Comment by lchristille** [comment]
I've found a solution that works on current Ubuntu 24.04 version.

The main problem is that newer versions of g++ are way more stricter than before.
(Ubuntu 24.04 comes with g++-14, Ubuntu 22.04 comes with g++-**11**).

I was able to build without changes running:
```bash
// Install gcc and g++ v.11
sudo apt install gcc-11 g++-11

// Configure v11 as alternatives
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 110 \
    --slave /usr/bin/gcc gcc /usr/bin/gcc-11

// Manually switch to v11
sudo update-alternatives --config g++
```

It could be possible, instead of switching globally, to use flags while building (e.g., `CXX=/usr/bin/g++-11` in Makefiles or `-DCMAKE_CXX_COMPILER=/usr/bin/g++-11` in CMake) but I haven't testing it yet.
